# Generated by Django 5.2.3 on 2025-09-17 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_contactus_options_contactus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره تلفن باید با 09 شروع شود و 11 رقم باشد.')], verbose_name='شماره موبایل'),
        ),
    ]
