# Generated by Django 5.2.3 on 2025-07-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-created_at',)},
        ),
    ]
