# Generated by Django 5.2.3 on 2025-07-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_room_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='services',
        ),
        migrations.AddField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(related_name='rooms', to='hotels.service'),
        ),
    ]
