# Generated by Django 5.2.3 on 2025-07-08 15:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
