# Generated by Django 5.2.3 on 2025-07-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='alt_text',
            field=models.CharField(max_length=100),
        ),
    ]
