# Generated by Django 5.2.3 on 2025-07-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_alter_roomimage_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='existing',
            field=models.BooleanField(default=True),
        ),
    ]
