# Generated by Django 5.2.3 on 2025-07-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='fullname',
        ),
    ]
