# Generated by Django 5.2.3 on 2025-07-30 06:16

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_alter_review_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',), 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-created_at',), 'verbose_name': 'اتاق', 'verbose_name_plural': 'اتاق ها'},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name': 'عکس اتاق', 'verbose_name_plural': 'عکس اتاق ها'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'سرویس', 'verbose_name_plural': 'سرویس ها'},
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='متن نظر'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.room', verbose_name='اتاق'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ظرفیت تعداد نفرات اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='room',
            name='existing',
            field=models.BooleanField(default=True, verbose_name='موجود بودن اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(related_name='rooms', to='hotels.service', verbose_name='سرویس ها اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='اندازه اتاق(به متر)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='alt_text',
            field=models.CharField(max_length=100, verbose_name='توضیح عکس'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='rooms/images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='عکس اصلی اتاق'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.room', verbose_name='اتاق'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=20, verbose_name='نام'),
        ),
    ]
