# Generated by Django 5.2.3 on 2025-08-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
