# Generated by Django 5.2.3 on 2025-09-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
