# Generated by Django 5.2.3 on 2025-08-21 21:16

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_booking_check_in_remove_booking_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=django_jalali.db.models.jDateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
