# Generated by Django 5.2.3 on 2025-08-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_booking_check_in_booking_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(null=True, verbose_name='تاریخ ورود'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(null=True, verbose_name='تاریخ خروج'),
        ),
    ]
