# Generated by Django 5.2.3 on 2025-08-22 17:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_booking_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام کامل')),
                ('national_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید ۱۰ رقم باشد.')], verbose_name='کد ملی')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره تلفن باید با ۰۹ شروع شده و ۱۱ رقم باشد.')], verbose_name='شماره تلفن')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='reservations.booking', verbose_name='رزرو')),
            ],
        ),
    ]
