# Generated by Django 5.2.3 on 2025-08-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_guest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'مهمان', 'verbose_name_plural': 'مهمان ها'},
        ),
    ]
