# Generated by Django 5.2.3 on 2025-09-01 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nights_stay',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد شب اقامت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق')], default='failed', max_length=20, verbose_name='وضعیت تراکنش'),
        ),
    ]
