# Generated by Django 5.2.3 on 2025-09-28 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='nights_stay',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد شب اقامت'),
        ),
    ]
