# Generated by Django 5.2.3 on 2025-07-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otp_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
